Update henson logging to allow propagate to be configurable
iheartradio/Henson-Logging pull request #41
Opened 2021-03-25 21:15 UTC by boguth

https://ihm-it.atlassian.net/browse/IHRACP-3480

Service applications implement the following code: 
```py
    app = Application(name) 
```
which calls this: 
```py
# instantiates a base python logger which inherits from the root logger.
# also implicitly sets a StreamHandler to the root logger which outputs to stderr
self.logger = logging.getLogger(self.name) # henson/base.py:64
```

Next, we typically call this in our service applications: 
```py
logger.init_app(app)
```
which causes any subsequent invocations of `logger` to invoke code which on first pass does this: 
```py
    # henson_logging/__init__.py:130
    'handlers': {
        'henson': {
            **self.app.settings['LOG_HANDLER_KWARGS'], <-- sets output to stdout
            'class': self.app.settings['LOG_HANDLER'],
            'formatter': self.app.settings['LOG_FORMATTER'],
        },
    }, 
    
   ....

  # henson_logging/__init__.py:147
  structlog.configure(
      processors=self.app.settings['LOG_PROCESSORS'],
      context_class=self.app.settings['LOG_CONTEXT_CLASS'],
      logger_factory=self.app.settings['LOG_FACTORY'], # <--- binds any subsequent structlog.get_logger calls to stdlib, which inherits from the root logger https://www.structlog.org/en/stable/api.html#structlog.stdlib.LoggerFactory
      wrapper_class=self.app.settings['LOG_WRAPPER_CLASS'],
      cache_logger_on_first_use=True,
  )

  self._logger = structlog.get_logger(self.app.name).bind()
```

This result of all this means that we now have two StreamHandlers, one handling events emitted by our logger and one handling events emitted by our base python logger - both of which inherit from the root logger. 

Each logger has a propagate setting which defaults to true. If it is true then:
```

 ...events logged to this logger will be passed to the handlers of higher level (ancestor) loggers, in addition to any handlers attached to this logger. Messages are passed directly to the ancestor loggers’ handlers - neither the level nor filters of the ancestor loggers in question are considered.

```
Reference: https://docs.python.org/3/library/logging.html#logging.Logger.propagate. 

This was causing us to outputs logs twice. Once to stdout and then to stderr. If we set propogate to false, this issue will stop. So I made that a configurable option.

2021-03-25 21:23 UTC, jnguyengit requested changes
Need to update change logs and versioning if we want this to go out right away. 
`setup.py` -> https://github.com/iheartradio/Henson-Logging/blob/master/setup.py#L23
`changes.rst` -> https://github.com/iheartradio/Henson-Logging/blob/master/CHANGES.rst

2021-03-25 22:01 UTC, Christian-Paul requested changes

2021-03-25 22:01 UTC, Christian-Paul commented on setup.py
>      author='Andy Dirnberger, Jon Banafato, Leonard Bedner, and others',
Add your name here and in AUTHORS.rst

2021-03-26 14:25 UTC, boguth commented on setup.py
>      author='Andy Dirnberger, Jon Banafato, Leonard Bedner, and others',
Done

2021-03-26 18:04 UTC, adityaghosh commented on henson_logging/__init__.py
> +        'PROPAGATE': True,
Just a comment: Does it make sense to call this `LOG_PROPAGATE` to be in line with all other settings 🤔 .

2021-03-29 15:49 UTC, boguth commented on henson_logging/__init__.py
> +        'PROPAGATE': True,
Yeah I like that

2021-03-29 15:52 UTC, adityaghosh approved these changes

2021-03-29 16:07 UTC, e-agbanyo requested changes
Remove the line number mentions, if these change in the future

2021-03-29 16:07 UTC, e-agbanyo commented on henson_logging/__init__.py
> +        # lines 83-91 use the state of Henson base
Remove the line number mentions, it would be confusing if those line shift from code changes in the future. Just leaving a reference to what the code is doing, not where it is, works.

2021-03-29 17:56 UTC, boguth commented on henson_logging/__init__.py
> +        # lines 83-91 use the state of Henson base
done

2021-03-29 18:21 UTC, jnguyengit approved these changes

2021-03-29 18:23 UTC, adityaghosh approved these changes

2021-03-29 19:48 UTC, Christian-Paul approved these changes

2021-03-29 20:01 UTC, lbedner commented on setup.py
> +    author='Andy Dirnberger, Jon Banafato, Leonard Bedner, Bo Guthrie, and others',
@boguth you're big time now, baby!

2021-03-29 20:01 UTC, lbedner approved these changes

2021-03-29 20:02 UTC, boguth commented on setup.py
> +    author='Andy Dirnberger, Jon Banafato, Leonard Bedner, Bo Guthrie, and others',
Heck yeah I am.

2021-03-29 20:14 UTC, e-agbanyo approved these changes

2021-03-29 21:10 UTC, merged